rootLogger=INFO, stdout
appender.stdout.type=console
appender.stdout.name=stdout
appender.stdout.layout.type=PatternLayout
appender.stdout.layout.pattern=%d [%t] %-5p %c - %m%n

#logger.net.socialgamer.cah.metrics=TRACE
#logger.org.postgresql=TRACE
#logger.net.socialgamer.cah.util.ChatFilter=TRACE
